### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lucgiffon**
Add "How to configure my promptS" section with example to let people know how to make 'permanent' changes of the prompt color.

### CODE REVIEW

**Comment by lucgiffon** [comment]
Thank you for your work.
I'm proposing this because I myself spend some time figuring how to change the default behavior of my terminal so that it uses your context-color script. I hope this isn't too specific and clear enough.
see you

**Comment by ramnes** [comment]
Hi @lucgiffon! :wave: 

Thank you for this PR, I'm sure it will help a lot of people. Could you please put those explanations directly inside the *Install* part, without the added titles?

**Comment by lucgiffon** [comment]
@ramnes like this?

**Comment by ramnes** [comment]
There are several little things that I don't like very much on that phrasing and way of presenting things. I went ahead and did this myself: https://github.com/ramnes/context-color/commit/c89c0f294e6c4066956091c44af201a49c2cee73. What do you think? Does it answer the questions you had when discovering `context-color`?

**Comment by lucgiffon** [comment]
Yes, I think it would have done.

**Comment by ramnes** [comment]
Great!

**Pull request closed without merging**
