### PR TITLE
Remove 'bc' dependency again and change shebang to use bash explicitly

### PR DESCRIPTION
**Pull request by Jibbajabbafic**
This should let it work with git bash on Windows and on systems that don't use bash as the default shell.

### CODE REVIEW

**Comment by ramnes** [comment]
I'm really divided on this issue. What's the more portable? `bash` or `bc`? I would have said `bc`, but Git Bash seems to be a good counterexample...

**Comment by Jibbajabbafic** [comment]
Well this is a bash script after all so I'd definitely say bash!

According to this page Debian does include bash for interactive shells so it should work with the new shebang: https://wiki.debian.org/Shell#:~:text=Debian%20uses%20Bash%20as%20the%20default%20interactive%20shell

**Comment by Jibbajabbafic** [comment]
Another alternative could be to use printf instead

**Comment by ramnes** [comment]
> Well this is a bash script after all so I'd definitely say bash!

It's not, it's a shell script that's quite POSIX so far. :)

> Another alternative could be to use printf instead

Yeah, that's exactly what I was thinking of. Do you want to try it?

**Comment by ramnes** [comment]
I did the modification to use printf instead of bc. Can you confirm that it works for you? :)

**Comment by Jibbajabbafic** [comment]
Hey @ramnes!

Sorry, yes you're right this is a POSIX compatible script. I'm only familiar with tcsh and bash so I assumed this was supposed to be bash script, my bad.

Thanks for making the changes though, I can confirm that it works in Git Bash 😄

**Comment by ramnes** [comment]
Great! :)

**Pull request closed without merging**
